name: 💡 Idea or Feedback
description: Suggest a new feature, improvement, or share early-stage thoughts.
title: "[Idea] "
labels: ["idea", "not ready"]
assignees: ["kaylawoodbury"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! This is a space for rough concepts, feedback, or feature suggestions that haven't been designed or scoped yet.

  - type: textarea
    id: summary
    attributes:
      label: Idea Summary
      description: A brief description of your idea or the feedback you're sharing.
      placeholder: "It would be helpful if we could..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Background / Context
      description: Why is this idea useful? What problem would it solve or opportunity would it create?
      placeholder: "This came up when..."
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes or Inspiration
      description: Links, screenshots, examples, or related conversations (optional).
      placeholder: "See this example from..."
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Checklist
      options:
        - label: I understand this is not a finalized feature request or task.
        - label: This idea has not been designed or added to a milestone yet.
        - label: I've checked the existing issues and this idea is not listed.