apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml
  - path: backend-service-patch.yaml
images:
  - name: ghcr.io/klimatbyran/frontend
    newTag: "4.3.2" # {"$imagepolicy": "flux-system:frontend:tag"}
