apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend-stage
resources:
  - ../../base
images:
  - name: ghcr.io/klimatbyran/frontend
    newTag: "4.5.2-rc.8" # {"$imagepolicy": "flux-system:frontend-stage:tag"}
